language: groovy
sudo: false
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master

before_install:
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh

- ala_travis_grails_setup_env

script:
- ala_travis_grails_build

env:
  global:
  - secure: bELSiy9/iB0UXjtp1KZAKLwao9HQMNBbWHxWjb6o8mSR6yguyFuCu2D3sAa3qzhLTnwie+FIENEY/ODaC7AMaGOAdgYmy3P44Cji9EhU5Z9UveZ5yUjaQt/pO65k8jVKAaUI+P+nRL/ZXqlnJsES9yxWD35WoSagEajH9xQNqCAW7REHYorKCUQNFypD6Xp0vOuFAatYskbWHorP61ukgzIvamcj8QwjH65uRUcIIDlHLIyxh/pX5t2SKj5PyNtYfhaLK80yOL7ODdC3kTWrna3B35pGYgBz0QypOW0QPFabefiLyCTeuK5VpPfc4WNxYcaWhboV76ZAsMh2Idc6jcE312NukH+xCuSbEOAiMud45Nghcf/Fuy5zWLgiSp17aH3EIWtU1KzQ9a2MlOovVTT3ZHl6eMrp5faqrQfPlhzHw4JnJxpePrX2j5JqXDU+zKptImQJZe6V2SIelCMEnzomEis4/8wOTiFtDGcJlME1Lgv7Z/DtPeRh0JJnZGNfh+QEWNJqjF/ASw6HA7FzgZYkA2FBAuhH34YYXm+TDjEG7HSok1Ctyam+W66qIuul7FOzAN28yzcTzFywSOEL28kqqf8vTjb2DGSF6XtryySMDzKpqpUdHdrojYDUztZwdWfO6UK0+MVc/aiZc3raxbWpH8cEnYoeSedHukrp9tA=
  - secure: eh/RZFu68xnsOvxBZO1BERtVVqDhNMBe656dmPhphfD+kMQhJTFznfqaijcOQ/OLFBosM/KHf7DA6M58+Li191rZs5iasPUWQRma77iD9mZxfr9XqadQ9vhHrBvZ8e1fZzCf5VAw5Bm6dRG+jSgT73a+a0h/rZIMu9A+L1p7MmJheLWgg2P+ANDqM1tCVEoVGS2BHdjJficR2JBMCUPOv09jrUQOdHf78Lmy3YwwwxtYH0btIuKTPzQoaLq4fhz8VUxfy11KKG1z9npZ0GWeLBrVTxK3OoausjURA065ljJgTJ6/6019PYt5pzomBGj8K9ovTcaE6E64POMqIMr/grAiq6D2wRp1lIbx4gl0RwTbii5DFWhEfHQqgWsm4HsQgsFS7tvGAWBhLb7ZLOcVqXkw7SSnite41Lo4gctEKElxKQl5BO1FxCxlt+q3RbLexJ41E1YCVaW/s4kXhj1spYwqIPcEppPAP+rJ1jKSVsg8IK+8qf6AanZwIkGyDS+YTeXERZcDdbhrmcxyKi+9MyXcwNqwHZtfYXqECv8Z9EdSeJgNqGfxRQgyQdgUigQXRBQQNh6OoLafwNwu23F+4a6yajpBcwbo5eyaXLjFZY7o8oniCEHXXVawmY+KenrlLX3llRlJpP/YpR13Hf1FcQtB+FxkH1amvIVto+DDUzY=
